<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>saucedemo_test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>04409185-ec45-4857-8083-b6aac869c3bf</testSuiteGuid>
   <testCaseLink>
      <guid>d90d5f20-48bb-471e-ac86-29c264cb62e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login DDT</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>60ea0493-463c-4597-b23e-a571214cc8d5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/saucedemo/user_login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>60ea0493-463c-4597-b23e-a571214cc8d5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>testType</value>
         <variableId>fb8c4392-beea-41de-8e6d-acaaed914286</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>60ea0493-463c-4597-b23e-a571214cc8d5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>6af46d3a-bce2-4e36-bdec-136661b2e1f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>60ea0493-463c-4597-b23e-a571214cc8d5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>290808b2-078d-4476-bed2-4f7a43f65544</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>60ea0493-463c-4597-b23e-a571214cc8d5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected</value>
         <variableId>30a8f723-513a-436f-9530-6bd4fd5889fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6bc9a13f-f1b9-4b9c-9297-aadc18acbded</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Filter Product</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>689590cd-d879-45b4-b5ed-c8dbd56b4fd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63854d27-63c3-4f3e-a2af-4d9be643d25e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b518c37-a995-4ba9-9e5a-2c52a6ea9a38</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Buy Product</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c156401-7a5c-40de-a520-794588077750</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d37490b9-3ecf-4c1b-9aea-f97a3e144e93</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
